apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: conjunta  # Namespace único
type: Opaque
stringData:
  POSTGRES_PASSWORD: "Admin123*"  # ¡Cambia esto en producción!
  POSTGRES_USER: "postgres"
  POSTGRES_MAIN_DB: "postgres"  # DB inicial
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: conjunta
data:
  01-init-databases.sql: |
    -- Bases de datos para microservicios
    CREATE DATABASE db_central;
    CREATE DATABASE db_facturacion;
    CREATE DATABASE db_inventario;
    
    -- Privilegios (ajusta según necesidades reales)
    GRANT ALL PRIVILEGES ON DATABASE db_central TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE db_facturacion TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE db_inventario TO postgres;
    
    -- Esquema inicial para ms-central (ejemplo)
    \c db_central
    CREATE TABLE IF NOT EXISTS agricultores (
      id UUID PRIMARY KEY,
      nombre VARCHAR(255) NOT NULL
    );
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: conjunta
spec:
  serviceName: postgresql  # Necesario para StatefulSet
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_MAIN_DB
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi  # Ajusta según necesidades
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  namespace: conjunta
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP